kind: Pod
apiVersion: v1
metadata:
    name: firstpod
    labels:
        app: fp
        team: red
    annotations:
        name: ajay
        country: India
spec:
    containers:
        - name: red
          image: redis
        - name: web
          image: httpd