apiVersion: v1
kind: Service
metadata:
    name: coupon-app
    labels:
        app: coupon-app
spec:
    type: NodePort
    ports:
        - port: 9097
          targetPort: 9097
          nodePort: 30288
    selector:
        app: coupon-app
