apiVersion: v1
kind: Service
metadata:
    name: docker-mysql
    labels:
        app: docker-mysql
spec:
    selector:
        app: docker-mysql
    type: NodePort
    ports:
        - nodePort: 30282
          port: 3306
          targetPort: 3306
          
          
